import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-cover  bg-no-repeat`}
  style={{
    backgroundImage: "url('https://static.vecteezy.com/system/resources/previews/003/144/020/non_2x/cyber-hacker-attack-background-skull-vector.jpg')",
  }}
      >
                <Navbar/>

        {children}
      </body>
    </html>
  );
}
